# Make it possible to use helix with tmux, remove delay when exiting insert mode
set -sg escape-time 0

set -g mouse on

set -s focus-events on

set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on

set -g monitor-activity on

set -g default-terminal "screen-256color"

# Open new panes in same dir
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g default-shell "/opt/homebrew/bin/fish"
set -g default-terminal "screen-256color"

set -g status-bg black
set -g status-fg white
set -g status-position bottom

setw -g window-status-current-style 'fg=black bg=cyan bold'
setw -g window-status-current-format ' #I:#W#F '

setw -g window-status-style 'fg=white bg=black dim'
setw -g window-status-format ' #I:#W#F '

setw -g window-status-activity-style 'fg=yellow bg=black bold'

set -g status-left '#[fg=green,bold]#S '
set -g status-right '#[fg=yellow]%Y-%m-%d %H:%M'
set -g status-left-length 20
set -g status-right-length 50